#
# $Id: Makefile,v 1.5 2000/09/27 01:27:51 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	xpm
VERSION=	3.4k
PORTREV=	1

PKG=		OPENxpm
NAME=		X PixMap library and its tools

VENDOR=		Arnaud Le Hors <lehors@sophia.inria.fr>, <http://www.inria.fr/koala/lehors/xpm.html>.
MASTER_SITES=	ftp://ring.nacsis.ac.jp/pub/X/opengroup/contrib/libraries/

USE_IMAKE=	yes

.include <port.mk>
