#
# $Id: Makefile,v 1.7 2001/03/02 09:22:08 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	xpm
VERSION=	3.4k
PORTREV=	2

PKG=		OPENxpm
NAME=		X PixMap library and its tools

VENDOR=		Arnaud Le Hors <lehors@sophia.inria.fr>, <http://www.inria.fr/koala/lehors/xpm.html>.
MASTER_SITES=	ftp://ring.nacsis.ac.jp/pub/X/opengroup/contrib/libraries/

USE_IMAKE=	yes
_MFLAGS+=	XPMINCDIR=${X11BASE}/share/include

.include <port.mk>
