#
# $Id: Makefile,v 1.3 1999/06/05 07:47:08 kunishi Exp $
#

PKG=		OPENxpm
NAME=		X PixMap library and its tools
VERSION=	3.4k
VENDOR=		Arnaud Le Hors <lehors@sophia.inria.fr>, <http://www.inria.fr/koala/lehors/xpm.html>.

DISTNAME=	xpm-${VERSION}
MASTER_SITES=	ftp://ring.nacsis.ac.jp/pub/X/opengroup/contrib/libraries/

USE_IMAKE=	yes

.include <port.mk>
