#
# $Id: Makefile,v 1.1 2000/07/14 11:14:08 kunishi Exp $
#

PORTNAME=	ja-mule-canna+wnn6

PKG=		GNUmule
NAME=		GNU Multi-lingual Emacs, with Canna and Wnn6 support

MASTERDIR=	${.CURDIR}/../../editors/mule

WITH_CANNA=	yes
WITH_WNN6=	yes

PROTOTYPE_IN=	${PKGDIR}/prototype.in.canna+wnn6

.include <${MASTERDIR}/Makefile>
