#
# $Id: Makefile,v 1.2 2000/09/27 01:27:44 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	ja-mule-canna+wnn6

PKG=		GNUmule
NAME=		GNU Multi-lingual Emacs, with Canna and Wnn6 support

MASTERDIR=	${.CURDIR}/../../editors/mule

WITH_CANNA=	yes
WITH_WNN6=	yes

PROTOTYPE_IN=	${PKGDIR}/prototype.in.canna+wnn6

.include <${MASTERDIR}/Makefile>
