#
# $Id: Makefile,v 1.3 2000/06/20 09:21:42 kunishi Exp $
#

SUBDIR+=	autoconf
SUBDIR+=	automake
SUBDIR+=	bison
SUBDIR+=	bmake
SUBDIR+=	cvs
SUBDIR+=	diffutils
SUBDIR+=	fileutils
SUBDIR+=	flex
SUBDIR+=	gcc
SUBDIR+=	gettext
SUBDIR+=	glib
SUBDIR+=	gmake
SUBDIR+=	libPropList
SUBDIR+=	libreadline
SUBDIR+=	libtool
SUBDIR+=	m4
SUBDIR+=	patch
SUBDIR+=	rcs
SUBDIR+=	zlib

.include <port.subdir.mk>
