#
# $Id: Makefile,v 1.6 2000/06/22 03:41:49 kunishi Exp $
#

SUBDIR+=	ORBit
SUBDIR+=	autoconf
SUBDIR+=	automake
SUBDIR+=	binutils
SUBDIR+=	bison
SUBDIR+=	bmake
SUBDIR+=	cvs
SUBDIR+=	diffutils
SUBDIR+=	fileutils
SUBDIR+=	flex
SUBDIR+=	gcc
SUBDIR+=	gcc27
SUBDIR+=	gettext
SUBDIR+=	glib
SUBDIR+=	gmake
SUBDIR+=	libPropList
SUBDIR+=	libreadline
SUBDIR+=	libtool
SUBDIR+=	m4
SUBDIR+=	patch
SUBDIR+=	rcs
SUBDIR+=	zlib
SUBDIR+=	zoularis

.include <port.subdir.mk>
