include ../../../conf/pkgbuild.conf

include ${PKGBUILD_CCS_MAKEFILE_DIR}/pre.mk
include ${PKGBUILD_CCS_MAKEFILE_DIR}/gnu_configure.mk
include ${PKGBUILD_CCS_MAKEFILE_DIR}/use_gmake.mk

DISTNAME=	patch-2.5
MASTER_SITES=	ftp://ring.nacsis.ac.jp/pub/GNU/patch/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/patch/

CORE_TOOLS=	yes

include ${PKGBUILD_CCS_MAKEFILE_DIR}/pkgbuild.mk
