#
# $Id: Makefile,v 1.6 1999/06/05 05:55:38 kunishi Exp $
#

PKG=		GNUpatch
NAME=		GNU patch
VERSION=	2.5
VENDOR=		${VENDOR_GNU}

DISTNAME=	patch-${VERSION}
MASTER_SITES=	ftp://ring.nacsis.ac.jp/pub/GNU/patch/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/patch/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

CORE_TOOLS=	yes

.include <port.mk>
