#
# $Id: Makefile,v 1.5 1999/06/05 05:44:29 kunishi Exp $
#

PKG=		GNUzip
NAME=		GNU compress utilities
VERSION=	1.2.4
VENDOR=		${VENDOR_GNU}

DISTNAME=	gzip-${VERSION}
MASTER_SITES=	ftp://ring.nacsis.ac.jp/pub/GNU/gzip/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/gzip/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes
USE_INSTALL_INFO=	yes

CORE_TOOLS=	yes

.include <port.mk>
