#
# $Id: Makefile,v 1.11 2002/03/18 12:10:29 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	autoconf
VERSION=	2.13
PORTREV=	2

PKG=	OPUCatcnf
NAME=	GNU autoconf, a tool for generating configure script automatically.
MAINTAINER=	kunishi@c.oka-pu.ac.jp

VENDOR=		${VENDOR_GNU}
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	autoconf
GNU_CONFIGURE=	yes
USE_GMAKE=	yes

CLASS_INFO=	info/autoconf.info info/standards.info

.include <port.mk>
