include ../../conf/pkgbuild.conf

include ${PKGBUILD_MAKEFILE_DIR}/pre.mk
include ${PKGBUILD_MAKEFILE_DIR}/gnu_configure.mk
include ${PKGBUILD_MAKEFILE_DIR}/use_gmake.mk

DISTNAME =	autoconf-2.13
MASTER_SITES =	ftp://ring.nacsis.ac.jp/pub/GNU/autoconf/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/autoconf/

include ${PKGBUILD_MAKEFILE_DIR}/pkgbuild.mk
