#
# $Id: Makefile,v 1.9 2000/09/27 01:27:39 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	autoconf
VERSION=	2.13
PORTREV=	1

PKG=	GNUautcnf
NAME=	GNU autoconf, a tool for generating configure script automatically.
MAINTAINER=	kunishi@c.oka-pu.ac.jp

VENDOR=		${VENDOR_GNU}
MASTER_SITES=	ftp://ring.nacsis.ac.jp/pub/GNU/autoconf/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/autoconf/
GNU_CONFIGURE=	yes
USE_GMAKE=	yes

CLASS_INFO=	info/autoconf.info info/standards.info

.include <port.mk>
