include ../../../conf/pkgbuild.conf

include ${PKGBUILD_CCS_MAKEFILE_DIR}/pre.mk
include ${PKGBUILD_CCS_MAKEFILE_DIR}/gnu_configure.mk
include ${PKGBUILD_CCS_MAKEFILE_DIR}/use_gmake.mk

DISTNAME =	libstdc++-2.8.1.1
MASTER_SITES =	ftp://ring.nacsis.ac.jp/pub/GNU/libstdc++/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/libstdc++/

CORE_TOOLS =	yes

include ${PKGBUILD_CCS_MAKEFILE_DIR}/pkgbuild.mk
