#
# $Id: Makefile,v 1.4 1999/06/05 05:46:31 kunishi Exp $
#

PKG=		GNUlstdc+
NAME=		GNU standard C++ library
VERSION=	2.8.1.1
VENDOR=		${VENDOR_GNU}

DISTNAME=	libstdc++-2.8.1.1
MASTER_SITES=	ftp://ring.nacsis.ac.jp/pub/GNU/libstdc++/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/libstdc++/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

CORE_TOOLS=	yes

.include <port.mk>
