#
# $Id: Makefile,v 1.3 2003/01/07 11:03:48 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	flex
VERSION=	2.5.4a
PORTREV=	2

PKG=		OPUCflex
NAME=		GNU lexical analyser
VENDOR=		${VENDOR_GNU}
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	non-gnu/flex

WRKSRC=		${WRKDIR}/${PORTNAME}-2.5.4

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <port.mk>
