#
# $Id: Makefile,v 1.1 2000/06/20 09:20:54 kunishi Exp $
#

PORTNAME=	flex
VERSION=	2.5.4a
PORTREV=	1

PKG=		GNUflex
NAME=		GNU lexical analyser
VENDOR=		${VENDOR_GNU}

MASTER_SITES=	ftp://ftp.jp.netbsd.org/pub/NetBSD/packages/distfiles/
WRKSRC=		${WRKDIR}/${PORTNAME}-2.5.4

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <port.mk>
