#
# $Id: Makefile,v 1.2 1999/05/19 10:17:38 kunishi Exp $
#

DISTNAME =	groff-1.11a
MASTER_SITES =	ftp://ring.nacsis.ac.jp/pub/GNU/groff/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/groff/

WRKSRC =	${WRKDIR}/groff-1.11
GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <port.mk>
