#
# $Id: Makefile,v 1.5 2000/09/27 01:27:54 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	groff
VERSION=	1.11a
PORTREV=	1

PKG=		GNUroff
NAME=		GNU roff package

VENDOR=		${VENDOR_GNU}
MASTER_SITES=	ftp://ring.nacsis.ac.jp/pub/GNU/groff/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/groff/

WRKSRC =	${WRKDIR}/${PORTNAME}-1.11
GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <port.mk>
