#
# $Id: Makefile,v 1.6 2002/03/15 11:34:46 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	groff
VERSION=	1.17.2
PORTREV=	1

PKG=		OPUCgroff
NAME=		GNU roff package

VENDOR=		${VENDOR_GNU}
MASTER_SITES=	ftp://ftp.dnsbalance.ring.gr.jp/pub/GNU/groff/ \
		ftp://ftp.gnu.org/pub/gnu/groff/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <port.mk>
