#
# $Id: Makefile,v 1.8 2001/11/28 11:53:58 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	bison
VERSION=	1.30
PORTREV=	1

PKG=		OPUCbison
NAME=		GNU project parser generator (yacc replacement)

VENDOR=		${VENDOR_GNU}
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	${PORTNAME}

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

CLASS_INFO=	info/bison.info

.include <port.mk>
