include ../../include/pre.mk

DISTNAME=	bison-1.27
MASTER_SITES=	ftp://ring.nacsis.ac.jp/pub/GNU/bison/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/bison/
GNU_CONFIGURE=	yes
USE_GMAKE=	yes

include ../../include/pkgbuild.mk