#
# $Id: Makefile,v 1.6 2000/05/17 06:42:46 kunishi Exp $
#

PORTNAME=	bison
VERSION=	1.27
PORTREV=	1

PKG=		GNUbison
NAME=		GNU project parser generator (yacc replacement)

VENDOR=		${VENDOR_GNU}
MASTER_SITES=	ftp://ring.nacsis.ac.jp/pub/GNU/bison/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/bison/
GNU_CONFIGURE=	yes
USE_GMAKE=	yes

CLASS_INFO=	info/bison.info

.include <port.mk>
