#
# $Id: Makefile,v 1.3 2000/05/17 06:42:47 kunishi Exp $
# 

PORTNAME=	youbin
VERSION=	2.13
PORTREV=	1

PKG=		OPENyoubi
NAME=		Youbin service package

VENDOR=		Agusa Lab., Nagoya Univ.
MASTER_SITES=	ftp://ftp.kyoto.wide.ad.jp/pub/net/

USE_IMAKE=	yes
PREFIX=		${LOCALBASE}

.include <port.mk>
