#
# $Id: Makefile,v 1.2 1999/06/05 09:25:48 kunishi Exp $
# 

PKG=		OPENyoubi
NAME=		Youbin service package
VERSION=	2.13
VENDOR=		Agusa Lab., Nagoya Univ.

DISTNAME=	youbin-${VERSION}
MASTER_SITES=	ftp://ftp.kyoto.wide.ad.jp/pub/net/

USE_IMAKE=	yes
PREFIX=		${LOCALBASE}

.include <port.mk>
