#
# $Id: Makefile,v 1.4 2000/09/27 01:27:52 kunishi Exp $
# 

.include <port.pre.mk>

PORTNAME=	youbin
VERSION=	2.13
PORTREV=	1

PKG=		OPENyoubi
NAME=		Youbin service package

VENDOR=		Agusa Lab., Nagoya Univ.
MASTER_SITES=	ftp://ftp.kyoto.wide.ad.jp/pub/net/

USE_IMAKE=	yes
PREFIX=		${LOCALBASE}

.include <port.mk>
