#
# $Id: Makefile,v 1.4 2000/05/17 06:42:48 kunishi Exp $
#

PORTNAME=	dviselect
VERSION=	1.3
PORTREV=	1

PKG=		OPENdvsel
NAME=		dviselect, dvi selecting utility

VENDOR=		Univ. Maryland Department of Comp. Sci.
DISTNAME=	${PORTNAME}
MASTER_SITES=	ftp://ftp.ee.duke.edu/archives/

USE_GMAKE=	yes

pre-install:
	${MKDIR} ${INSTPREFIX}/bin
	${MKDIR} ${INSTPREFIX}/man/man1

.include <port.mk>
