#
# $Id: Makefile,v 1.1 1999/05/21 05:16:23 kunishi Exp $
#

DISTNAME=	dviselect
PKGNAME=	dviselect-1.3
MASTER_SITES=	ftp://ftp.ee.duke.edu/archives/

USE_GMAKE=	yes

pre-install:
	${MKDIR} ${WRK_BASEDIR}/bin
	${MKDIR} ${WRK_BASEDIR}/man/man1

.include <port.mk>
