#
# $Id: Makefile,v 1.1 2000/07/14 11:14:08 kunishi Exp $
#

PORTNAME=	ja-mule-wnn6

PKG=		GNUmule
NAME=		GNU Multi-lingual Emacs, with Wnn6 support

MASTERDIR=	${.CURDIR}/../../editors/mule

WITH_WNN6=	yes

PROTOTYPE_IN=	${PKGDIR}/prototype.in.wnn6

.include <${MASTERDIR}/Makefile>
