#
# $Id: Makefile,v 1.2 1999/05/17 11:54:22 kunishi Exp $
#

DISTNAME =	diffutils-2.7
MASTER_SITES =	ftp://ring.nacsis.ac.jp/pub/GNU/diffutils/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/diffutils/
GNU_CONFIGURE=	yes
CONFIGURE_ARGS +=	--program-prefix=g
USE_GMAKE=	yes

.include <port.mk>
