#
# $Id: Makefile,v 1.1 2000/01/07 01:43:50 kunishi Exp $
#
# This file is only for maitenance.
# Users do not need to use this makefile in any case.

CVSROOT=	bloodstone:/export/share/cvsroot
CORE_TOOLS+=	Mk Template

all:	none

none:
	/usr/bin/true

checkout-core-ports:
	cvs -d ${CVSROOT} checkout ${CORE_TOOLS}
