#
# $Id: Makefile,v 1.1 2000/06/05 08:58:39 kunishi Exp $
#

SUBDIR+=	VFlib2
SUBDIR+=	acroread4
SUBDIR+=	dvipsk
SUBDIR+=	dviselect
SUBDIR+=	freetype
SUBDIR+=	groff
SUBDIR+=	gs
SUBDIR+=	gv
SUBDIR+=	jvf
SUBDIR+=	makejvf
SUBDIR+=	platex
SUBDIR+=	ptex
SUBDIR+=	watanabe-vf
SUBDIR+=	xdvik

.include <port.subdir.mk>
