#
# $Id: Makefile,v 1.3 2000/06/22 03:40:54 kunishi Exp $
#

SUBDIR+=	VFlib2
SUBDIR+=	acroread4
SUBDIR+=	dvipsk
SUBDIR+=	dviselect
SUBDIR+=	freetype
SUBDIR+=	groff
SUBDIR+=	gs
SUBDIR+=	gv
SUBDIR+=	jvf
SUBDIR+=	makejvf
SUBDIR+=	platex
SUBDIR+=	platex209
SUBDIR+=	psutils
SUBDIR+=	ptex
SUBDIR+=	watanabe-vf
SUBDIR+=	xdvik

.include <port.subdir.mk>
