#
# $Id: Makefile,v 1.4 1999/06/17 11:02:52 kunishi Exp $
# 

PKG=		OPENkinp2
NAME=		kinput2, an input server for easy input of Japanese text
VERSION=	3.0
VENDOR=		Makoto Ishisone <ishisone@sra.co.jp>

DISTNAME=	kinput2-v3
PKGNAME=	kinput2-canna+wnn6-${VERSION}
MASTER_SITES=	ftp://ftp.sra.co.jp/pub/x11/kinput2/

USE_IMAKE=	yes

LIB_DEPENDS=	OPENcanna:${PORTSDIR}/japanese/Canna

.include <port.mk>
