#
# $Id: Makefile,v 1.2 1999/06/06 06:55:12 kunishi Exp $
# 

PKG=		OPENkinp2
NAME=		kinput2, an input server for easy input of Japanese text
VERSION=	2.0.3beta2
VENDOR=		Makoto Ishisone <ishisone@sra.co.jp>

DISTNAME=	kinput2-v3-beta3
PKGNAME=	kinput2-canna+wnn6-${VERSION}
MASTER_SITES=	ftp://ftp.sra.co.jp/pub/x11/kinput2/

USE_IMAKE=	yes

.include <port.mk>
