#
# $Id: Makefile,v 1.2 2000/01/18 12:11:10 kunishi Exp $
# 

PKG=		GNUglib
NAME=		some useful routines for C programming
VERSION=	1.2.3
VENDOR=		http://www.gtk.org/

DISTNAME=	glib-${VERSION}
MASTER_SITES=	ftp://ftp.gimp.org/pub/gtk/v1.2/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

CLASS_INFO=	info/glib.info

.include <port.mk>
