#
# $Id: Makefile,v 1.3 2000/05/17 06:42:46 kunishi Exp $
# 

PORTNAME=	glib
VERSION=	1.2.3
PORTREV=	1

PKG=		GNUglib
NAME=		some useful routines for C programming

VENDOR=		http://www.gtk.org/
MASTER_SITES=	ftp://ftp.gimp.org/pub/gtk/v1.2/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

CLASS_INFO=	info/glib.info

.include <port.mk>
