#
# $Id: Makefile,v 1.1 1999/07/23 09:06:43 kunishi Exp $
# 

PKG=		GNUglib
NAME=		some useful routines for C programming
VERSION=	1.2.3
VENDOR=		http://www.gtk.org/

DISTNAME=	glib-${VERSION}
MASTER_SITES=	ftp://ftp.gimp.org/pub/gtk/v1.2/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes
USE_INSTALL_INFO=	yes

.include <port.mk>
