#
# $Id: Makefile,v 1.7 2000/05/17 06:53:28 kunishi Exp $
#

PORTNAME=	bash
VERSION=	2.04
PORTREV=	1

PKG=		GNUbash
NAME=		GNU bash

VENDOR=		${VENDOR_GNU}
MASTER_SITES =	ftp://ring.nacsis.ac.jp/pub/GNU/bash/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/bash/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

CLASS_INFO=	info/bash.info
CLASS_SHELL=	bin/bash

.include <port.mk>
