#
# $Id: Makefile,v 1.10 2001/11/28 10:51:46 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	bash
VERSION=	2.05a
PORTREV=	1

PKG=		OPUCbash
NAME=		GNU bash

VENDOR=		${VENDOR_GNU}
MASTER_SITES =	ftp://ftp.dnsbalance.ring.gr.jp/pub/GNU/bash/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/bash/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

CLASS_INFO=	info/bash.info
CLASS_SHELL=	bin/bash

.include <port.mk>
