#
# $Id: Makefile,v 1.7 1999/08/27 11:51:20 kunishi Exp $
#

PKG=		GNUpatch
NAME=		GNU patch
VERSION=	2.5
VENDOR=		${VENDOR_GNU}

DISTNAME=	patch-${VERSION}
MASTER_SITES=	ftp://ring.nacsis.ac.jp/pub/GNU/patch/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/patch/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <port.mk>
