#
# $Id: Makefile,v 1.1 1999/05/21 08:13:05 kunishi Exp $
#

DISTNAME=	lynx2-8-1
PKGNAME=	lynx-2.8.1
MASTER_SITES=	http://sol.slcc.edu/lynx/release2-8-1/

GNU_CONFIGURE=	yes
MAKEFILE=	makefile
INSTALL_TARGET=	install install-help

WRKSRC=		${WRKDIR}/lynx2-8-1

.include <port.mk>
