#
# $Id: Makefile,v 1.2 1999/06/06 06:51:28 kunishi Exp $
#

PKG=		OPENlynx
NAME=		lynx, a non-graphical, text-based World Wide Web client.
VERSION=	2.8.1
VENDOR=		lynx-dev@sig.net <http://www.slcc.edu/lynx/>

DISTNAME=	lynx2-8-1
PKGNAME=	lynx-${VERSION}
MASTER_SITES=	http://sol.slcc.edu/lynx/release2-8-1/

GNU_CONFIGURE=	yes
MAKEFILE=	makefile
INSTALL_TARGET=	install install-help

WRKSRC=		${WRKDIR}/lynx2-8-1

.include <port.mk>
