#
# $Id: Makefile,v 1.3 2000/05/17 06:42:48 kunishi Exp $
#

PORTNAME=	lynx
VERSION=	2.8.1
PORTREV=	1

PKG=		OPENlynx
NAME=		lynx, a non-graphical, text-based World Wide Web client.

VENDOR=		lynx-dev@sig.net <http://www.slcc.edu/lynx/>
DISTNAME=	lynx2-8-1
MASTER_SITES=	http://sol.slcc.edu/lynx/release2-8-1/

GNU_CONFIGURE=	yes
MAKEFILE=	makefile
INSTALL_TARGET=	install install-help

WRKSRC=		${WRKDIR}/lynx2-8-1

.include <port.mk>
