#
# $Id: Makefile,v 1.1 2000/06/22 12:25:36 kunishi Exp $
#

PORTNAME=	xeyes
VERSION=	1.0
PORTREV=	1

PKG=		OPENxeyes
NAME=		xeyes
VENDOR=		X Consortium

MASTER_SITES=	ftp://ftp.xfree86.org/pub/XFree86/3.3.6/source/
DISTNAME=	X336contrib
EXTRACT_SUFX=	.tgz

WRKSRC=		${WRKDIR}/contrib/programs/xeyes

USE_IMAKE=	yes

.include <port.mk>
