#
# $Id: Makefile,v 1.1 2000/09/06 10:55:17 kunishi Exp $
#

PORTNAME=	mysql
VERSION=	3.22.32
PORTREV=	1

PKG=		OPENmysql
NAME=		Multithreaded SQL database

MASTER_SITES=	http://www.mysql.com/Downloads/MySQL-3.22/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

CLASS_INFO=	info/mysql.info

.include <port.mk>
