#
# $Id: Makefile,v 1.2 1999/05/17 11:54:25 kunishi Exp $
#

DISTNAME =	rcs-5.7
MASTER_SITES = 	ftp://ring.nacsis.ac.jp/pub/GNU/rcs/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/rcs/
GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <port.mk>
