#
# $Id: Makefile,v 1.6 2000/09/27 01:27:43 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	rcs
VERSION=	5.7
PORTREV=	1

PKG=		GNUrcs
NAME=		GNU rcs, the Revision Control System

VENDOR=		${VENDOR_GNU}
MASTER_SITES = 	ftp://ring.nacsis.ac.jp/pub/GNU/rcs/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/rcs/
GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <port.mk>
