#
# $Id: Makefile,v 1.3 1999/06/05 05:23:09 kunishi Exp $
#

PKG=		GNUrcs
NAME=		GNU rcs, the Revision Control System
VERSION=	5.7
VENDOR=		${VENDOR_GNU}

DISTNAME =	rcs-${VERSION}
MASTER_SITES = 	ftp://ring.nacsis.ac.jp/pub/GNU/rcs/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/rcs/
GNU_CONFIGURE=	yes
USE_GMAKE=	yes
USE_INSTALL_INFO=	yes

.include <port.mk>
