#
# $Id: Makefile,v 1.3 2000/09/27 01:27:55 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	psutils
VERSION=	1.17
PORTREV=	1

PKG=		OPENpsutl
NAME=		Utilities for manipulating PostScript documents
VENDOR=		Angus J. C. Duggan <angus@harlequin.co.uk>

#MASTER_SITES=	ftp://ftp.dcs.ed.ac.uk/pub/ajcd/
MASTER_SITES=	ftp://ftp.jp.freebsd.org/pub/FreeBSD/distfiles/
DISTNAME=	${PORTNAME}-p17

WRKSRC=		${WRKDIR}/${PORTNAME}
USE_PERL5=	yes
MAKEFILE=	Makefile.unix

.include <port.mk>
