#
# $Id: Makefile,v 1.1 2000/07/14 09:49:31 kunishi Exp $
#

PORTNAME=	emcws20-wnn6

PKG=		GNUemwn6
NAME=		Emacs20, with Wnn6 support

MASTERDIR=	${.CURDIR}/../../editors/emcws20

WITH_WNN6=	yes

PROTOTYPE_IN=	${PKGDIR}/prototype.in.wnn6

.include <${MASTERDIR}/Makefile>
