#
# $Id: Makefile,v 1.3 2000/09/27 01:27:44 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	emcws20-wnn6

PKG=		GNUemcws
NAME=		Emacs20, with Wnn6 support

MASTERDIR=	${.CURDIR}/../../editors/emcws20

WITH_WNN6=	yes

PROTOTYPE_IN=	${PKGDIR}/prototype.in.wnn6

.include <${MASTERDIR}/Makefile>
