#
# $Id: Makefile,v 1.2 2000/07/14 11:33:04 kunishi Exp $
#

PORTNAME=	emcws20-wnn6

PKG=		GNUemcws
NAME=		Emacs20, with Wnn6 support

MASTERDIR=	${.CURDIR}/../../editors/emcws20

WITH_WNN6=	yes

PROTOTYPE_IN=	${PKGDIR}/prototype.in.wnn6

.include <${MASTERDIR}/Makefile>
