#
# $Id: Makefile,v 1.2 2000/09/27 01:27:44 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	ja-mule-canna

PKG=		GNUmule
NAME=		GNU Multi-lingual Emacs, with Canna support

MASTERDIR=	${.CURDIR}/../../editors/mule

WITH_CANNA=	yes

PROTOTYPE_IN=	${PKGDIR}/prototype.in.canna

.include <${MASTERDIR}/Makefile>
