#
# $Id: Makefile,v 1.1 2000/07/14 11:14:08 kunishi Exp $
#

PORTNAME=	ja-mule-canna

PKG=		GNUmule
NAME=		GNU Multi-lingual Emacs, with Canna support

MASTERDIR=	${.CURDIR}/../../editors/mule

WITH_CANNA=	yes

PROTOTYPE_IN=	${PKGDIR}/prototype.in.canna

.include <${MASTERDIR}/Makefile>
