#
# $Id: Makefile,v 1.4 2000/05/17 06:42:47 kunishi Exp $
#

PORTNAME=	gawk
VERSION=	3.0.3
PORTREV=	1

PKG=		GNUawk
NAME=		GNU awk

VENDOR=		${VENDOR_GNU}
MASTER_SITES=	ftp://ring.nacsis.ac.jp/pub/GNU/gawk/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/gawk/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

CLASS_INFO=	info/gawk.info

.include <port.mk>
