#
# $Id: Makefile,v 1.6 2002/03/15 11:09:27 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	gawk
VERSION=	3.1.0
PORTREV=	1

PKG=		OPUCgawk
NAME=		GNU awk

VENDOR=		${VENDOR_GNU}
MASTER_SITES=	ftp://ftp.dnsbalance.ring.gr.jp/pub/GNU/gawk/ \
		ftp://ftp.gnu.org/pub/gnu/gawk/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

CLASS_INFO=	info/gawk.info info/gawkinet.info

.include <port.mk>
