#
# $Id: Makefile,v 1.2 1999/06/05 08:01:09 kunishi Exp $
#

PKG=		GNUawk
NAME=		GNU awk
VERSION=	3.0.3
VENDOR=		${VENDOR_GNU}

DISTNAME=	gawk-${VERSION}
MASTER_SITES=	ftp://ring.nacsis.ac.jp/pub/GNU/gawk/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/gawk/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes
USE_INSTALL_INFO=	yes

.include <port.mk>
