#
# $Id: Makefile,v 1.1 2001/03/23 00:52:33 kunishi Exp $
#

PORTNAME=	gperf
VERSION=	2.7.2
PORTREV=	1

PKG=		GNUgperf
NAME=		a GNU program that generates perfect hash functions

VENDOR=		${VENDOR_GNU}
MASTER_SITES=	ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/gperf/ \
		ftp://ftp.gnu.org/pub/gnu/gperf/

USE_GMAKE=	yes
GNU_CONFIGURE=	yes

CLASS_INFO=	info/gperf.info

.include <port.mk>
