#
# $Id: Makefile,v 1.2 2002/03/18 11:29:11 kunishi Exp $
#

PORTNAME=	python
VERSION=	2.3
PORTREV=	1

PKG=		OPUCpythn
NAME=		Python language

MASTER_SITES=	http://python.org/ftp/python/${VERSION}/
DISTNAME=	Python-${VERSION}
DISTFILES=	${DISTNAME}.tgz

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <port.mk>
