#
# $Id: Makefile,v 1.1 2001/03/02 14:34:06 kunishi Exp $
#

PORTNAME=	x11-ssh-askpass
VERSION=	1.2.0
PORTREV=	1

PKG=		OPENaskpx
NAME=		a X11-based passphrase dialog for use with OpenSSH

MASTER_SITES=	http://www.jmknoble.cx/software/x11-ssh-askpass/

USE_IMAKE=	yes
PREFIX=		/usr

.include <port.mk>
