#
# $Id: Makefile,v 1.3 2003/02/27 06:52:05 kunishi Exp $
#

PORTNAME=	x11-ssh-askpass
VERSION=	1.2.4.1
PORTREV=	1

PKG=		OPUCaskpx
NAME=		a X11-based passphrase dialog for use with OpenSSH

MASTER_SITES=	http://www.jmknoble.cx/software/x11-ssh-askpass/

USE_IMAKE=	yes
PREFIX=		/usr

.include <port.mk>
