#
# $Id: Makefile,v 1.1 2000/06/05 09:01:50 kunishi Exp $
#

SUBDIR+=	archivers
SUBDIR+=	databases
SUBDIR+=	devel
SUBDIR+=	editors
SUBDIR+=	elisp
SUBDIR+=	graphics
SUBDIR+=	japanese
SUBDIR+=	lang
SUBDIR+=	mail
SUBDIR+=	misc
SUBDIR+=	net
SUBDIR+=	print
SUBDIR+=	security
SUBDIR+=	shells
SUBDIR+=	textproc
SUBDIR+=	www
SUBDIR+=	x11
SUBDIR+=	xml

.include <port.subdir.mk>
