#
# $Id: Makefile,v 1.1 2002/12/27 01:47:52 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	mktemp
VERSION=	1.4
PORTREV=	1

PKG=		OPUCmktmp
NAME=		a small program to allow safe temporary file creation from shell scripts

MASTER_SITES=	ftp://ftp.mktemp.org/pub/mktemp/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <port.mk>
