#
# $Id: Makefile,v 1.1 1999/11/17 02:53:44 kunishi Exp $
#

PKG=	NBSDlukft
NAME=	Luke Mewburn's ftp
VERSION=	1.1
VENDOR=	NetBSD Users' Group, http://www.netbsd.org/

DISTNAME=	lukemftp-${VERSION}
MASTER_SITES=	ftp://ftp.netbsd.org/pub/NetBSD/misc/lukemftp/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <port.mk>
