#
# $Id: Makefile,v 1.2 2000/01/06 09:31:37 kunishi Exp $
#

PKG=		OPENtiff
NAME=		TIFF Software Distribution
VERSION=	3.5.4
VENDOR=		Silicon Graphics, Inc.

DISTNAME=	tiff-v3.5.4
PKGNAME=	tiff-${VERSION}
MASTER_SITES=	ftp://ftp.onshore.com/pub/libtiff/ \
		http://www.libtiff.org/

HAS_CONFIGURE=	yes
CONFIGURE_ARGS+=	--noninteractive

.include <port.mk>
