#
# $Id: Makefile,v 1.3 2000/09/27 01:27:45 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	aalib
VERSION=	1.2
PORTREV=	1

PKG=		OPENaalib
NAME=		An ascii art library
VENDOR=		Jan Hubicka (hubicka@paru.cas.cz) et al.

MASTER_SITES=	ftp://ftp.ta.jcu.cz/pub/aa/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

CLASS_INFO=	info/aalib.info

.include <port.mk>
