#
# $Id: Makefile,v 1.2 2000/06/16 11:52:03 kunishi Exp $
#

PORTNAME=	aalib
VERSION=	1.2
PORTREV=	1

PKG=		OPENaalib
NAME=		An ascii art library
VENDOR=		Jan Hubicka (hubicka@paru.cas.cz) et al.

MASTER_SITES=	ftp://ftp.ta.jcu.cz/pub/aa/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

CLASS_INFO=	info/aalib.info

.include <port.mk>
