#
# $Id: Makefile,v 1.1 2000/06/05 04:14:47 kunishi Exp $
#

PORTNAME=	findutils
VERSION=	4.1
PORTREV=	1

PKG=		GNUfind
NAME=		GNU find utilities
MASTER_SITES=	ftp://ftp.gnu.org/pub/gnu/findutils/

GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--program-prefix=g
USE_GMAKE=	yes

CLASS_INFO=	info/find.info

.include <port.mk>
