#
# $Id: Makefile,v 1.2 2000/09/27 01:27:53 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	findutils
VERSION=	4.1
PORTREV=	1

PKG=		GNUfind
NAME=		GNU find utilities
MASTER_SITES=	ftp://ftp.gnu.org/pub/gnu/findutils/

GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--program-prefix=g
USE_GMAKE=	yes

CLASS_INFO=	info/find.info

.include <port.mk>
