#
# $Id: Makefile,v 1.2 2003/02/26 10:58:20 kunishi Exp $
#

PORTNAME=	libiconv
VERSION=	1.8
PORTREV=	1

PKG=		OPUCiconv
NAME=		GNU character set conversion library

MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	${PORTNAME}

GNU_CONFIGURE=	yes
CONFIGURE_ARGS+=	--enable-static
USE_GMAKE=	yes

.include <port.mk>
