#
# $Id: Makefile,v 1.1 2001/11/28 13:27:55 kunishi Exp $
#

PORTNAME=	libiconv
VERSION=	1.7
PORTREV=	1

PKG=		OPUCiconv
NAME=		GNU character set conversion library

MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	${PORTNAME}

GNU_CONFIGURE=	yes
CONFIGURE_ARGS+=	--enable-static
USE_GMAKE=	yes

.include <port.mk>
