#
# $Id: Makefile,v 1.4 2000/06/16 12:07:38 kunishi Exp $
#

SUBDIR+=	aalib
SUBDIR+=	java3d
SUBDIR+=	jpeg
SUBDIR+=	libungif
SUBDIR+=	mpeg-lib
SUBDIR+=	netpbm
SUBDIR+=	png
SUBDIR+=	pnmtopng
SUBDIR+=	tgif
SUBDIR+=	tiff
SUBDIR+=	wmicons
SUBDIR+=	xpm
SUBDIR+=	xv

.include <port.subdir.mk>
