#
# $Id: Makefile,v 1.8 2000/06/23 11:19:09 kunishi Exp $
#

SUBDIR+=	ImageMagick
SUBDIR+=	aalib
SUBDIR+=	gd
SUBDIR+=	hdf
SUBDIR+=	java3d
SUBDIR+=	jbigkit
SUBDIR+=	jpeg
SUBDIR+=	libungif
SUBDIR+=	mpeg-lib
SUBDIR+=	netpbm
SUBDIR+=	png
SUBDIR+=	pnmtopng
SUBDIR+=	tgif
SUBDIR+=	tiff
SUBDIR+=	wmicons
SUBDIR+=	xpm
SUBDIR+=	xv

.include <port.subdir.mk>
