#
# $Id: Makefile,v 1.1 2001/11/30 12:38:26 kunishi Exp $
#

PORTNAME=	xlhtml
VERSION=	0.3
PORTREV=	1

PKG=		OPUCxlhtm
NAME=		Utilities converting Excel and PowerPoint files to HTML and text

MASTER_SITES=	http://www.xlhtml.org/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <port.mk>
