#!/bin/sh
PATH=/usr/local/sbin:/usr/bin:/bin

case "$1" in
'start')
	if [ -f /usr/local/sbin/sshd2 ] ; then
		/usr/local/sbin/sshd2 >/dev/null 2>&1
	fi
	;;
'stop')
	if test -f /etc/ssh2/sshd2_22.pid; then
		kill `cat /etc/ssh2/sshd2_22.pid` > /dev/null 2>&1
	fi
	;;
*)
	echo "usage: $0 {start|stop}"
	;;
esac
