#
# $Id: Makefile,v 1.3 1999/05/17 11:28:19 kunishi Exp $
#

DISTNAME =	m4-1.4
MASTER_SITES =	ftp://ring.nacsis.ac.jp/pub/GNU/m4/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/m4/
GNU_CONFIGURE=	yes
CONFIGURE_ARGS+=	--program-prefix=g
USE_GMAKE=	yes

.include <port.mk>
