#
# $Id: Makefile,v 1.5 2000/01/19 01:19:20 kunishi Exp $
#

PKG=		GNUm4
NAME=		GNU m4, an implementation of the traditional Unix macro processor.
VERSION=	1.4
VENDOR=		${VENDOR_GNU}

DISTNAME =	m4-1.4
MASTER_SITES =	ftp://ring.nacsis.ac.jp/pub/GNU/m4/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/m4/
GNU_CONFIGURE=	yes
CONFIGURE_ARGS+=	--program-prefix=g
USE_GMAKE=	yes

CLASS_INFO=	info/m4.info

.include <port.mk>
