include ../../conf/pkgbuild.conf

include ${PKGBUILD_MAKEFILE_DIR}/pre.mk
include ${PKGBUILD_MAKEFILE_DIR}/gnu_configure.mk
include ${PKGBUILD_MAKEFILE_DIR}/use_gmake.mk

DISTNAME =	m4-1.4
MASTER_SITES =	ftp://ring.nacsis.ac.jp/pub/GNU/m4/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/m4/

include ${PKGBUILD_MAKEFILE_DIR}/pkgbuild.mk
