#
# $Id: Makefile,v 1.1 2000/05/17 12:42:08 kunishi Exp $
# 

PORTNAME=	libproplist
VERSION=	0.10.1
PORTREV=	1

PKG=		WMlbprp
NAME=		Property library for gnome and WindowMaker

VENDOR=		http://www.windowmaker.org/
MASTER_SITES=	ftp://ftp.windowmaker.org/pub/libs/
DISTNAME=	libPropList-${VERSION}

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <port.mk>
