#
# $Id: Makefile,v 1.6 2000/05/17 06:42:47 kunishi Exp $
#

PORTNAME=	ncftp
VERSION=	3.0.1
PORTREV=	1

PKG=		OPENncftp
NAME=		NcFTP, a free set of programs that use FTP.
VENDOR=		NcFTP Software <http://www.NcFTP.com/>

DISTNAME=	${PORTNAME}-${VERSION}-src
MASTER_SITES=	ftp://ftp.ncftp.com/ncftp/
WRKSRC=		${WRKDIR}/${PORTNAME}-${VERSION}

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <port.mk>
