#
# $Id: Makefile,v 1.5 2000/05/15 09:03:06 kunishi Exp $
#

PKG=		OPENncftp
NAME=		NcFTP, a free set of programs that use FTP.
VERSION=	3.0.1
VENDOR=		NcFTP Software <http://www.NcFTP.com/>

DISTNAME=	ncftp-${VERSION}-src
PKGNAME=	ncftp-${VERSION}
MASTER_SITES=	ftp://ftp.ncftp.com/ncftp/
WRKSRC=		${WRKDIR}/ncftp-${VERSION}

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <port.mk>
