#
# $Id: Makefile,v 1.2 1999/05/17 11:54:23 kunishi Exp $
#

DISTNAME =	fileutils-4.0
MASTER_SITES =	ftp://ring.nacsis.ac.jp/pub/GNU/fileutils/ \
		ftp:/ftp.media.kyoto-u.ac.jp/pub/GNU/fileutils/
GNU_CONFIGURE=	yes
CONFIGURE_ARGS +=	--program-prefix=g
USE_GMAKE=	yes

.include <port.mk>
