#
# $Id: Makefile,v 1.6 2001/11/28 11:02:40 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	libreadline
VERSION=	4.2a
PORTREV=	1

PKG=		OPUClibrd
NAME=		GNU readline library

VENDOR=		${VENDOR_GNU}
DISTNAME=	readline-${VERSION}
MASTER_SITES=	ftp://ftp.dnsbalance.ring.gr.jp/pub/GNU/readline/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/readline/ \
		ftp://ftp.gnu.org/pub/gnu/readline/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

CLASS_INFO=	info/history.info info/readline.info info/rluserman.info

.include <port.mk>
