#
# $Id: Makefile,v 1.4 2000/05/17 06:42:46 kunishi Exp $
#

PORTNAME=	libreadline
VERSION=	4.0
PORTREV=	1

PKG=		GNUlibrdl
NAME=		GNU readline library

VENDOR=		${VENDOR_GNU}
DISTNAME=	readline-${VERSION}
MASTER_SITES=	ftp://ring.nacsis.ac.jp/pub/GNU/readline/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/readline/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

CLASS_INFO=	info/history.info info/readline.info

.include <port.mk>
