#
# $Id: Makefile,v 1.2 1999/06/05 04:54:22 kunishi Exp $
#

PKG=		GNUlibrdl
NAME=		GNU readline library
VERSION=	4.0
VENDOR=		${VENDOR_GNU}

DISTNAME=	readline-${VERSION}
PKGNAME=	libreadline-${VERSION}
MASTER_SITES=	ftp://ring.nacsis.ac.jp/pub/GNU/readline/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/readline/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes
USE_INSTALL_INFO=	yes

.include <port.mk>
