#
# $Id: Makefile,v 1.1 2000/07/14 09:49:31 kunishi Exp $
#

PORTNAME=	emcws20-canna+wnn6

PKG=		GNUemcw6
NAME=		Emacs20, with Canna and Wnn6 support

MASTERDIR=	${.CURDIR}/../../editors/emcws20

WITH_CANNA=	yes
WITH_WNN6=	yes

PROTOTYPE_IN=	${PKGDIR}/prototype.in.canna+wnn6

.include <${MASTERDIR}/Makefile>
