#
# $Id: Makefile,v 1.3 2000/09/27 01:27:43 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	emcws20-canna+wnn6

PKG=		GNUemcws
NAME=		Emacs20, with Canna and Wnn6 support

MASTERDIR=	${.CURDIR}/../../editors/emcws20

WITH_CANNA=	yes
WITH_WNN6=	yes

PROTOTYPE_IN=	${PKGDIR}/prototype.in.canna+wnn6

.include <${MASTERDIR}/Makefile>
