#
# $Id: Makefile,v 1.3 1999/06/05 04:50:47 kunishi Exp $
# 

PKG=		GNUgetxt
NAME=		GNU gettext package
VERSION=	0.10.35
VENDOR=		${VENDOR_GNU}

DISTNAME=	gettext-${VERSION}
MASTER_SITES=	ftp://alpha.gnu.ai.mit.edu/gnu/ \
		ftp://alpha.gnu.org/pub/gnu/

GNU_CONFIGURE=	yes
USE_GMAKE=	yes
USE_INSTALL_INFO=	yes

.include <port.mk>
