#
# $Id: Makefile,v 1.2 2000/07/14 11:33:03 kunishi Exp $
#

PORTNAME=	emcws20-canna

PKG=		GNUemcws
NAME=		Emacs20, with Canna support

MASTERDIR=	${.CURDIR}/../../editors/emcws20

WITH_CANNA=	yes

PROTOTYPE_IN=	${PKGDIR}/prototype.in.canna

.include <${MASTERDIR}/Makefile>
