#
# $Id: Makefile,v 1.1 2000/07/14 09:49:31 kunishi Exp $
#

PORTNAME=	emcws20-canna

PKG=		GNUemcan
NAME=		Emacs20, with Canna support

MASTERDIR=	${.CURDIR}/../../editors/emcws20

WITH_CANNA=	yes

PROTOTYPE_IN=	${PKGDIR}/prototype.in.canna

.include <${MASTERDIR}/Makefile>
