#
# $Id: Makefile,v 1.3 2000/09/27 01:27:43 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	emcws20-canna

PKG=		GNUemcws
NAME=		Emacs20, with Canna support

MASTERDIR=	${.CURDIR}/../../editors/emcws20

WITH_CANNA=	yes

PROTOTYPE_IN=	${PKGDIR}/prototype.in.canna

.include <${MASTERDIR}/Makefile>
