#
# $Id: Makefile,v 1.3 2000/06/16 11:24:26 kunishi Exp $
#

SUBDIR+=	Xaw3d
SUBDIR+=	fvwm-i18n
SUBDIR+=	fvwm95-i18n
SUBDIR+=	gtk
SUBDIR+=	kinput2
SUBDIR+=	kterm
SUBDIR+=	windowmaker-i18n
SUBDIR+=	xdaliclock
SUBDIR+=	xpbiff

.include <port.subdir.mk>
