#
# $Id: Makefile,v 1.6 2000/09/27 01:27:59 kunishi Exp $
#

SUBDIR+=	Xaw3d
SUBDIR+=	afterstep
SUBDIR+=	fvwm-i18n
SUBDIR+=	fvwm95-i18n
SUBDIR+=	gtk
SUBDIR+=	kinput2
SUBDIR+=	kterm
#SUBDIR+=	windowmaker-i18n
SUBDIR+=	xdaliclock
SUBDIR+=	xeyes
SUBDIR+=	xpbiff

.include <port.subdir.mk>
