#
# $Id: Makefile,v 1.5 2000/06/22 12:26:23 kunishi Exp $
#

SUBDIR+=	Xaw3d
SUBDIR+=	afterstep
SUBDIR+=	fvwm-i18n
SUBDIR+=	fvwm95-i18n
SUBDIR+=	gtk
SUBDIR+=	kinput2
SUBDIR+=	kterm
SUBDIR+=	windowmaker-i18n
SUBDIR+=	xdaliclock
SUBDIR+=	xeyes
SUBDIR+=	xpbiff

.include <port.subdir.mk>
