#
# $Id: Makefile,v 1.1 2001/11/30 12:38:25 kunishi Exp $
#

PORTNAME=	cole
VERSION=	2.0.1
PORTREV=	1

PKG=		OPUCcole
NAME=		A free C OLE library

MASTER_SITES=	${MASTER_SITE_FREEBSD_LOCAL}
MASTER_SITE_SUBDIR=	sobomax

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <port.mk>
