#
# bootstrap makefile for building md5
# $Id: Makefile.md5,v 1.2 2000/05/02 05:06:49 kunishi Exp $
#

TARGET_CMD=	md5

include ${TOPDIR}/bootstrap/config.mk

DISTNAME=	MD5
DISTFILES=	MD5.tar.Z
SRCURL=		ftp://ftp.aist-nara.ac.jp/pub/Security/tool/md5/

include ${BOOTSTRAPDIR}/rule.mk

fetch:
	if [ ! -f ${DISTDIR}/${DISTFILES} ]; then \
	  (cd ${DISTDIR} && ${FTP} ${SRCURL}${DISTFILES}); \
	fi

extract:	${FETCH_COOKIE}
	${MKDIR} ${WORKDIR}/${DISTNAME}
	cd ${WORKDIR}/${DISTNAME} && \
	  (${GUNZIP} ${DISTDIR}/${DISTFILES} | ${EXTRACT_CMD} -)

patch:		${EXTRACT_COOKIE}
	${DO_NADA}

configure:	${PATCH_COOKIE}
	${DO_NADA}

build:		${CONFIGURE_COOKIE}
	cd ${WORKDIR}/${DISTNAME} && ${MAKE} CC=${TMPPREFIX}/bin/gcc

install:	${BUILD_COOKIE}
	if [ ! -f ${INSTALL_COOKIE} ]; then \
	  ${INSTALL_PROGRAM} ${WORKDIR}/${DISTNAME}/md5 ${TMPPREFIX}/bin; \
	fi
	${TOUCH} ${INSTALL_COOKIE}
