#
# $Id: Makefile,v 1.1 2001/11/12 12:32:46 kunishi Exp $
#

PORTNAME=	mpeg2dec
VERSION=	0.2.0
PORTREV=	1

PKG=		OPUCmp2dc
NAME=		Mpeg2 Decoder

MASTER_SITES=	http://imagemagick.sourceforge.net/http/delegates/
WRKSRC=		${WRKDIR}/${PORTNAME}-0.2.1-cvs/

GNU_CONFIGURE=	yes
CONFIGURE_ARGS+=	--disable-warnings --enable-shared
USE_GMAKE=	yes

.include <port.mk>
