#
# $Id: Makefile,v 1.3 1999/06/05 04:09:05 kunishi Exp $
#

PKG=		GNUautmak
NAME=		GNU automake utilitites
VERSION=	1.4
VENDOR=		${VENDOR_GNU}

DISTNAME=	automake-${VERSION}
MASTER_SITES=	ftp://ring.nacsis.ac.jp/pub/GNU/automake/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/automake/
GNU_CONFIGURE=	yes
USE_GMAKE=	yes
USE_INSTALL_INFO=	yes

.include <port.mk>
