#
# $Id: Makefile,v 1.4 2000/01/18 11:53:53 kunishi Exp $
#

PKG=		GNUautmak
NAME=		GNU automake utilitites
VERSION=	1.4
VENDOR=		${VENDOR_GNU}

DISTNAME=	automake-${VERSION}
MASTER_SITES=	ftp://ring.nacsis.ac.jp/pub/GNU/automake/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/automake/
GNU_CONFIGURE=	yes
USE_GMAKE=	yes

CLASS_INFO=	info/automake.info

.include <port.mk>
