#
# $Id: Makefile,v 1.7 2001/11/30 12:50:33 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	automake
VERSION=	1.5
PORTREV=	1

PKG=		OPUCautmk
NAME=		GNU automake utilitites

VENDOR=		${VENDOR_GNU}
MASTER_SITES=	ftp://ftp.dnsbalance.ring.gr.jp/pub/GNU/automake/ \
		ftp://ftp.media.kyoto-u.ac.jp/pub/GNU/automake/
GNU_CONFIGURE=	yes
USE_GMAKE=	yes

CLASS_INFO=	info/automake.info

.include <port.mk>
