#
# $Id: Makefile,v 1.3 1999/06/06 07:03:10 kunishi Exp $
#

PKG=		OPENxdlcl
NAME=		X melting digital clock
VERSION=	2.13
VENDOR=		Jamie Zawinski <jwz@jwz.org>

DISTNAME=	xdaliclock-${VERSION}
MASTER_SITES=	http://www.jwz.org/xdaliclock/

USE_IMAKE=	yes

.include <port.mk>
