#
# $Id: Makefile,v 1.1 1999/11/16 03:47:44 kunishi Exp $
#

PKG=	GNUrsync
NAME=	GNU file syncing tool
VERSION=	2.3.2
VENDOR=	${VENDOR_GNU}

DISTNAME=	rsync-${VERSION}
MASTER_SITES=	ftp://samba.anu.edu.au/pub/rsync/

GNU_CONFIGURE=	yes

.include <port.mk>
