#
# $Id: Makefile,v 1.4 2000/09/27 01:27:53 kunishi Exp $
#

.include <port.pre.mk>

PORTNAME=	rsync
VERSION=	2.4.3
PORTREV=	1

PKG=	GNUrsync
NAME=	GNU file syncing tool

VENDOR=	${VENDOR_GNU}
MASTER_SITES=	ftp://samba.anu.edu.au/pub/rsync/

GNU_CONFIGURE=	yes

.include <port.mk>
