#
# $Id: Makefile,v 1.2 2000/05/17 06:42:47 kunishi Exp $
#

PORTNAME=	rsync
VERSION=	2.3.2
PORTREV=	1

PKG=	GNUrsync
NAME=	GNU file syncing tool

VENDOR=	${VENDOR_GNU}
MASTER_SITES=	ftp://samba.anu.edu.au/pub/rsync/

GNU_CONFIGURE=	yes

.include <port.mk>
